# Site
repository: arrashapl/arrashapl.github.io
#favicon: images/favicon.ico

# Company info
name: Arrasha Holdings
title: A diversified holding company
#email: 
website: arrashapl.github.io

# About Section
# about_title: About Me
about_profile_image: images/logo.png 
link: https://arrasha-holdings.github.io
about_content: | # this will include new lines to allow paragraphs
 Arrasha Holdings is a privately held diversified holding company with investments across a range of industries. We are committed to building long-term value through strategic acquisitions and operational excellence. Our portfolio companies benefit from our expertise, resources, and network.
  
# Portfolio Section
portfolio_title: Portfolio Companies

# Values Section
values_title: Our Values

# Team Section
#team_title: Leadership Team

# Contact Section
contact_title: Contact Us
contact_content: | # this will include new lines to allow paragraphs
  For inquiries, please contact us at info@arrashaholdings.com.

# Footer
#footer_show_references: true

# Build settings
remote_theme: risjain/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-analytics

#jekyll_analytics:
#  GoogleAnalytics:
#    id: UA-176591083-1      # Required - replace with your tracking id

# Google services
#google_analytics: UA-176591083-1

#google_site_verification: kYpCqA3JumA-uix2hTrzJCwQaZaIGgMxoUy3P7wANJw

#Include Brave
include: .well-known